apiVersion: v1
kind: ConfigMap
metadata:
  name: scaffork_django-django-configmap
data:
  PYTHONUNBUFFERED: '1'
  DB_ENGINER: django.db.backends.postgresql
  DB_DATA_BASE: scaffork_django_dev
  DB_USER: scaffork_django
  DB_PASSWORD: 123@mudar
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  GOOGLE_APPLICATION_CREDENTIALS: scaffork_django-gcp-credentials.json